const syntax = {
  italic: {
    name: "ITALIC",
    scope: [
      "comment",
      "storage.modifier",
      "punctuation.definition.comment",
      "entity.other",
      "variable.language",
      "support.type.vendored",
      "support.constant.vendored",
      "markup.quote",
      "markup.italic",
      "tag.decorator.js entity.name.tag.js",
      "tag.decorator.js punctuation.definition.tag.js",
      "keyword.control.clojure",
      "source.clojure meta.symbol.dynamic",
      "keyword.other.this.cs",
      "keyword.other.base.cs",
      "variable.other.member.c",
      "support.type.core.rust",
      "variable.other.object.property",
      "variable.other.property",
      "source.r meta.function.r keyword.control.r",
      "comment.line.roxygen.r keyword",
      "comment.line.roxygen.r variable.parameter.r",
      "keyword.control.inheritance.coffee",
      "comment.block.documentation.phpdoc.php keyword",
      "keyword.other.array.phpdoc.php",
      "storage.type.modifier",
      "comment.block.javadoc.java keyword",
      "comment.block.javadoc.java variable.parameter.java",
      "keyword.operator.documentation.powershell",
      "storage.type.scala",
      "variable.parameter.function.language.special",
      "comment.block.documentation.scala keyword",
      "comment.block.documentation.scala variable.parameter",
      "support.function.builtin.go",
      "constant.other.symbol.hashkey.ruby",
      "constant.other.symbol.hashkey.ruby punctuation.definition.constant.ruby",
      "constant.other.symbol.ruby",
      "source.vala storage.type.generic",
      "constant.other.table-name",
      "constant.other.placeholder",
      "variable.other.field",
      "entity.alias.import.go",
      "source.swift keyword.other.declaration-specifier",
      "support.variable.swift",
      "keyword.other.capture-specifier",
      "text.tex support.function.emph",
      "constant.other.math",
      "support.function.textit",
      "entity.name.footnote",
      "entity.name.function.directive.graphql",
      "source.graphql support.type.enum",
      "source.ocaml entity.name.filename",
      "source.reason entity.name.filename",
      "abstract.definition.fsharp keyword",
      "abstract.definition.fsharp entity",
      "function.anonymous keyword",
      "entity.name.record.field.accessor.elm",
      "support.type.primitive",
      "support.type.builtin",
      "keyword.type.cs",
      "storage.type.built-in",
      "storage.type.primitive",
      "source.python support.type.python",
      "storage.type.core.rust",
      "source.swift support.type",
      "source.go storage.type",
      "storage.type.php",
      "storage.type.function.kotlin",
      "entity.name.type.kotlin",
      "support.type.julia",
      "variable.other.member",
      "keyword.other.import",
      "keyword.package",
      "keyword.import",
      "source.wsd keyword.control.diagram",
      "keyword.language.gherkin.feature.step",
      "source.hlsl storage.type.basic",
      "source.apex keyword.type",
      "sharing.modifier",
      "source.nim storage.type.concrete",
      "meta.preprocessor.pragma.nim",
      "storage.type.integral",
      "entity.name.scope-resolution.function.call",
      "support.class.builtin",
      "comment.block.documentation storage.type.class",
      "source.tf meta.keyword.string",
      "source.tf meta.keyword.number",
      "source.scala entity.name.class",
      "meta.import keyword.control",
      "keyword.control.export",
      "source.vue meta.directive punctuation.separator.key-value",
      "keyword.local.lua",
      "markup.list",
      "markup.mark.constrained markup.mark",
      "markup.block.open",
    ],
    settings: {
      fontStyle: "italic",
    },
  },
  bold: {
    name: "BOLD",
    scope: [
      "keyword",
      "keyword.control",
      "keyword.operator",
      "keyword.other.template",
      "keyword.other.substitution",
      "storage.type.function.arrow",
      "constant.other.color",
      "punctuation.accessor",
      "entity.name.section",
      "markup.bold",
      "markup.bold string",
      "markdown.heading",
      "markup.inline.raw punctuation.definition.raw",
      "markup.heading",
      "storage.type.function.pug",
      "storage.type.function.python",
      "storage.type.annotation",
      "punctuation.bracket.angle",
      "keyword.other.new",
      "punctuation.separator.question-mark.cs",
      "storage.type.generic.wildcard",
      "source.go keyword.operator",
      "punctuation.separator.namespace",
      "constant.other.symbol.ruby punctuation.definition.constant.ruby",
      "variable.parameter",
      "support.function.builtin.rust",
      "storage.type.function.coffee",
      "entity.name.variable.parameter",
      "punctuation.separator.hash.cs",
      "constant.other.symbol.ruby punctuation.definition.constant.ruby",
      "constant.other.symbol.hashkey.ruby punctuation.definition.constant.ruby",
      "meta.function.parameters variable.other",
      "entity.name.type.annotation.kotlin",
      "storage.type.objc",
      "parameter.variable.function",
      "markup punctuation.definition",
      "punctuation.section.directive",
      "punctuation.definition.preprocessor",
      "source.ruby punctuation.definition.variable",
      "punctuation.separator.method",
      "support.function.textbf",
      "source.graphql support.type.builtin",
      "source.ocaml variable.interpolation string",
      "entity.name.function.definition.special.constructor",
      "entity.name.function.definition.special.member.destructor.",
      "meta.function.parameters variable punctuation.definition.variable.php",
      "source.wsd keyword.other.activity",
      "keyword.control.class.ruby",
      "keyword.control.def.ruby",
      "keyword.function.go",
      "keyword.other.fn.rust",
      "markup.other.anchor",
      "markup.list.bullet",
      "markup.list punctuation.definition",
    ],
    settings: {
      fontStyle: "bold",
      // fontWeight: 500,
    },
  },
  boldItalic: {
    name: "BOLD-ITALIC",
    scope: [
      "markup.bold markup.italic",
      "markup.italic markup.bold",
      "markup.quote markup.bold",
      "markup.bold markup.italic string",
      "markup.italic markup.bold string",
      "markup.quote markup.bold string",
      "text.html punctuation.section.embedded",
      "variable.other.c",
      "storage.modifier.lifetime.rust",
      "entity.name.lifetime.rust",
      "source.rust meta.attribute.rust",
      "meta.attribute.id entity.other.attribute-name",
      "source.ocaml punctuation.definition.tag emphasis",
      "source.tf entity.name",
      "markup.quote punctuation.definition",
      "markup.fenced_code punctuation.definition",
      "fenced_code.block.language",
    ],
    settings: {
      fontStyle: "bold italic",
      // fontWeight: 500,
    },
  },
  normal: {
    name: "NORMAL",
    scope: [
      "keyword.begin.tag.ejs",
      "source.python meta.function.decorator.python support.type.python",
      "source.cs keyword.other",
      "keyword.other.var.cs",
      "source.go keyword",
      "storage.modifier.static.rust",
      "variable.parameter.r",
      "variable.parameter.handlebars",
      "storage.modifier.import",
      "storage.modifier.package",
      "meta.class.identifier storage.modifier",
      "keyword.operator.other.powershell",
      "source.css variable.parameter",
      "string.interpolated variable.parameter",
      "source.apacheconf keyword",
      "keyword.other.julia",
      "storage.modifier.using.vala",
      "source.objc keyword.other.property.attribute",
      "source.sql keyword.other",
      "keyword.other.using.vala",
      "keyword.operator.function.infix",
      "keyword.control.directive",
      "keyword.other.rust",
      "keyword.other.declaration-specifier.swift",
      "entity.name.function.swift",
      "keyword.control.class",
      "keyword.control.def",
      "punctuation.definition.variable",
      "entity.name.section.latex",
      "source.ocaml keyword markup.underline",
      "source.ocaml constant.language constant.numeric entity.other.attribute-name.id.css",
      "source.reason entity.other.attribute-name constant.language constant.numeric",
      "keyword.format.specifier.fsharp",
      "entity.name.section.fsharp",
      "binding.fsharp keyword",
      "binding.fsharp keyword.symbol",
      "record.fsharp keyword",
      "keyword.symbol.fsharp",
      "entity.name.section.fsharp keyword",
      "namespace.open.fsharp keyword",
      "namespace.open.fsharp entity",
      "storage.type",
      "source.cpp keyword.other",
      "source.c keyword.other",
      "keyword.other.unit",
      "storage.modifier.array.bracket",
      "keyword.control.default",
      "meta.import.haskell keyword",
      "keyword.declaration.dart",
      "source.wsd keyword.other",
      "keyword.other.skinparam",
      "source.css keyword.control",
      "source.css keyword.operator",
      "keyword.language.gherkin.feature.scenario",
      "keyword.control.cucumber.table",
      "source.toml entity.other.attribute-name",
      "source.toml keyword",
      "keyword.other.nim",
      "source.nim keyword.other.common.function",
      "source.nim keyword.other",
      "source.scala keyword.declaration",
      "source.scala entity.name.class.declaration",
      "keyword.control.lua",
    ],
    settings: {
      fontStyle: "",
    },
  },
};

export default syntax;
